export const commonMessages = {
  LOGIN_SUCCESS: "Login successful",
  LOGOUT_SUCCESS: "Logout successful",
  USER_NOT_FOUND: "User not found",
  INTERNAL_SERVER_ERROR: "Internal server error occurred",
  REGISTER_SUCCESS: "User registered successfully",
  INVALID_PASSWORD: "Invalid password",
  UNAUTHORIZED: "Unauthorized",
  SUCCESS: "Success",
  IDEA_SUBMITED: "Idea submitted",
  COMMENT_ADDED: "Comment added",
  IDEA_ID_REQUIRED: "Idea id is required",
  VOTE_ADDED: "Vote recorded",
  VOTE_EXIST: "Vote already recorded",
  IDEA_NOT_FOUND: "Idea not found",
  FORBIDDEN: "Insufficient permissions",
  IDEA_UPDATED: "Idea updated",
  IDEA_DELETED: "Idea deleted",
  URL_NOT_FOUND: "Url you are trying to access is not found",
  TOO_MANY_REQ: "Too many requests, please try again later.",
  ACCESS_DENIED: "Access denied",
};
