export const commonMessages = {
  LOGIN_SUCCESS: "Login successful",
  LOGOUT_SUCCESS: "Logout successful",
  USER_NOT_FOUND: "User not found",
  INTERNAL_SERVER_ERROR: "Internal server error occurred",
  REGISTER_SUCCESS: "User registered successfully",
  INVALID_PASSWORD: "Invalid password",
  UNAUTHORIZED: "Unauthorized",
  SUCCESS: "Success",
  FORBIDDEN: "Insufficient permissions",
  URL_NOT_FOUND: "Url you are trying to access is not found",
  TOO_MANY_REQ: "Too many requests, please try again later.",
  ACCESS_DENIED: "Access denied",
  USER_CREATED: "User created successfully",
  USER_NOT_CREATED: "User not created",
  SCHOOL_CREATE_SUCCESS: "School created successfully",
  SCHOOL_UPDATE_SUCCESS: "School updated successfully",
  SUBDOMAIN_NOT_FOUND: "Subdomain not found",
  SUBDOMAIN_ALREADY_EXISTS: "Subdomain already exists",
  SCHOOL_NOT_FOUND: "School not found",
};
